version: "3"
services:
  # frontend:
  #   build: frontend/.
  #   ports:
  #     - 80:80
  # backend:
  #   build: backend/.
  #   ports:
  #     - 8080:8080
  #     - 3000:3000
  #   depends_on:
  #     - mongo
  mongo:
    image: mongo
    environment: 
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017