version: '3'
services:
    # frontend:
    #     build: ./frontend
    #     ports:
    #         - 80:80
    backend:
        build: ./backend
        restart: always
        ports:
            - 8080:8080
            - 50051:50051
        depends_on:
            - mongo
    mongo:
      image: mongo
      ports:
          -  27017:27017